import type { Metadata } from "next";
import "./globals.css";
import * as stylex from "@stylexjs/stylex";
import { layoutStyle } from "./layout.stylex";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body {...stylex.props(layoutStyle.body)}>{children}</body>
    </html>
  );
}
